name: Docker Build & Migrate DB & Deploy for EC2

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'staging'
      - 'production'
      - 'preproduction'

jobs:
  build:
    name: Docker Build & Migrate DB & ECR Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Action Started Notification
      - run: echo ''
#         uses: mikesprague/teams-incoming-webhook-action@v1
#         with:
#           github-token: ${{ github.token }}
#           webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
#           deploy-card: true
#           title: 'Git Action Started'
#           color: 'info'
      - name: Import PGP(gpg) credentials
        run: echo ''
#         run: |
#           echo -e "$PGP_PRIVATE_KEY" | gpg --import
#         env:
#           PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      - name: Ckeck GPG Key
        run: echo ''
#         run: |
#           gpg --version
#           gpg --list-key paul@capa.ai
      - name: Install sops
        run: echo ''
