name: Docker Build & Migrate DB & Deploy for EC2
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'staging'
      - 'production'
      - 'preproduction'

jobs:
  date:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - run: date
