name: Docker Build & Migrate DB & Deploy for EC2

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'staging'
      - 'production'
      - 'preproduction'

jobs:
  build:
    name: Docker Build & Migrate DB & ECR Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Action Started Notification
        run: echo ''
