name: ECR CI/CD

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ test ]

# 환경설정
env:
  DOCKER_IMAGE: 042568141900.dkr.ecr.ap-northeast-2.amazonaws.com/identicalhirang
  VERSION: ${{ github.sha }}
  NAME: hirang-nodejs-ecr

jobs:
  # 빌드 Job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: identicalhirang
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$VERSION .
          docker push $REGISTRY/$REPOSITORY:$VERSION          
  # 배포 Job
  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH remote ecr pull
        uses: appleboy/ssh-action@v0.1.4
        with:
         host: ${{secrets.AWS_HIRANG_IP}}
         username: ${{secrets.AWS_HIRANG_USERNAME}}
         key: ${{secrets.AWS_HIRANG_SSH}}
#        향후 ec2에서 sh파일을 만들어서 실행 
         script: |    
           aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin "$(aws sts get-caller-identity --query Account --output text).dkr.ecr.ap-northeast-2.amazonaws.com"
           docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi $(docker images -q ${{ env.DOCKER_IMAGE }})
           docker pull ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
           docker run -d -p 8090:8080 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
           
           
           
#       - name: Login to ECR
#         uses: docker/login-action@v2
#         with:
#           registry: 042568141900.dkr.ecr.ap-northeast-2.amazonaws.com
# #           registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
#           username: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
#           password: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}         
          
