name: 기능별 테스트

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
       symbol-list: [ko,jp,tw,cn,us]
    name: strategy test
    runs-on: ubuntu-latest
    steps:
      - name: $
        run: |
          echo symbol=$
        
    
