name: 기능별 테스트

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
       region: [ko,jp,tw]
    name: strategy test
    runs-on: ubuntu-latest
    steps:
      - name: ${{ matrix.region }}
        run: |
          echo ${{ matrix.region }}   
  check:
    name: gpg check 
    runs-on: ubuntu-latest
    steps: 
                  
      - name: Import PGP(gpg) credentials
        run: |
          echo -e "$PGP_PRIVATE_KEY" | gpg --import
        env:
          PGP_PRIVATE_KEY: ${{ secrets.GPG_HIRANG01_PRIVATE_KEY }}

#       - name: Import GPG key
#         id: import_gpg
#         uses: crazy-max/ghaction-import-gpg@v5
#         with:
#           gpg_private_key: ${{ secrets.GPG_HIRANG01_PRIVATE_KEY }}
#           passphrase: ${{ secrets.GPG_HIRANG01_PASSPHRASE }}
#       - name: List keys
#         run: gpg -K
          
      - name: Ckeck GPG Key
        run: |
          gpg --version
          gpg --list-key 
    
