name: 기능별 테스트

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
       region: [ko,jp,tw]
    name: strategy test
    runs-on: ubuntu-latest
    steps:
      - name: ${{ matrix.region }}
        run: |
          echo ${{ matrix.region }}   
  check:
    name: gpg check 
    runs-on: ubuntu-latest
    steps: 
      - name: Import PGP(gpg) credentials
        run: |
          echo -e "$GPG_HIRANG_PRIVATE" | gpg --import
        env:
          PGP_PRIVATE_KEY: ${{ secrets.GPG_HIRANG_PRIVATE }}
      
      - name: Ckeck GPG Key
        run: |
          gpg --version
          gpg --list-key 
    
