name: 기능별 테스트

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
       region: [ko,jp,tw,cn,us]
    name: strategy test
    runs-on: ubuntu-latest
    steps:
      - name: ${{ matrix.region }}
        run: |
          echo ${{ matrix.region }}
        
    
