name: 기능별 테스트

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
       region: [ko,jp,tw]
    name: strategy test
    runs-on: ubuntu-latest
    steps:
      - name: ${{ matrix.region }}
        run: |
          echo ${{ matrix.region }}   
  check:
    name: gpg check 
    runs-on: ubuntu-latest
    steps: 
      - name: Ckeck GPG Key
        run: |
          gpg --version
          gpg --list-key 
                  
#       - name: Import PGP(gpg) credentials
#         run: |
#           echo -e "${{ secrets.GPG_HIRANG01_PRIVATE_KEY }}" | gpg --import
#         env:
#           PGP_PRIVATE_KEY: ${{ secrets.GPG_HIRANG01_PRIVATE_KEY }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_HIRANG01_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_HIRANG01_PASSPHRASE }}
      - name: List keys
        run: |
          gpg -K
          gpg --list-keys
          
      - name: Install sops
        env:
          SOPS_VERSION: v3.7.1
        run: |
          wget https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux
          chmod +x ./sops-${SOPS_VERSION}.linux
          sudo mv ./sops-${SOPS_VERSION}.linux /usr/local/bin/sops
          
      
    
